### ISSUE TITLE
The link to download activitynet-caption features seems broken, could you please check it?

### ISSUE THREAD

**Issue by chenchengfd** [gingsi/coot-videotext#1]
The link to download activitynet-caption features seems broken, could you please check it?

**Comment by gingsi** [comment]
There's two links to google drive in there, one from us and one from the original creators of the features. I just checked and they are working on my end.

Can you please check if both do not work and also please post exactly the error message etc. Also if you have a google account, it can sometimes help to be logged in when downloading public things from google drive.

**Comment by chenchengfd** [comment]
> There's two links to google drive in there, one from us and one from the original creators of the features. I just checked and they are working on my end.
> 
> Can you please check if both do not work and also please post exactly the error message etc. Also if you have a google account, it can sometimes help to be logged in when downloading public things from google drive.

Thanks for your kind reply. I have checked the two link, and they still don't work. I search the error message in google, where the blog write these error can be solved by log in google drive. But I can't create google account, because i'm not in America.
The error message is shown as below:  
""Sorry, you can't view or download this file at this time.
Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.''""

**Comment by gingsi** [comment]
Thanks for posting the error message. We will try to find a new mirror to host the activitynet-captions features.

**Comment by chenchengfd** [comment]
Thanks!

**Comment by gingsi** [comment]
Dataset is now available via torrent (see the README). If you have problems, follow the Troubleshooting section.

Best
