### ISSUE TITLE
Video captioning code release

### ISSUE THREAD

**Issue by PipiZong** [gingsi/coot-videotext#11]
Hi,

Thanks for sharing your great work!!!
I am wondering when you're going to release the video captioning code? Will it be September 2021?

**Comment by gingsi** [comment]
Hi,

You might just get it as a late christmas present together with our updated paper version on January 8th.

**Comment by PipiZong** [comment]
Hi,

Thank you for your quick response and great news!!! I'm looking forward to it!

**Comment by gingsi** [comment]
Check out the latest updates while you wait for the captioning code which will be released in the next 2 weeks.

**Comment by lzlzlizi** [comment]
Hi, any new updates about the captioning codes?

**Comment by gingsi** [comment]
Hi, sorry for the delay, but I have not forgotten it. Should be done this month

**Comment by lzlzlizi** [comment]
Thanks, deeply looking forward to it!

**Comment by gingsi** [comment]
Video captioning code is online!
