### ISSUE TITLE
 No module named 'mart'

### ISSUE THREAD

**Issue by ericwang0701** [gingsi/coot-videotext#16]
I just tried to run the new Video Captioning code, but it seems some files about MART are missing. 

Thank you so much for publishing the Video Captioning code. Can't wait to try it out.

**Comment by gingsi** [comment]
Could you please post the full error message?

**Comment by ericwang0701** [comment]
To be more precise, I have set up the project and downloaded the COOT output Embeddings and Pretrained models. When I ran ` python train_caption.py -c config/caption/paper2020/yc2_100m_coot_vidclip_mart.yaml --validate --load_model provided_models_caption/yc2_100m_coot_vidclip_mart.pth` , it gave me the following errors:

`Traceback (most recent call last):
  File "train_caption.py", line 11, in <module>
    from mart import arguments_mart
ModuleNotFoundError: No module named 'mart'`

**Comment by gingsi** [comment]
Thanks, fixed. Please reopen if the issue persists.
