### ISSUE TITLE
Can you provide a Baidu cloud disk database download link?

### ISSUE THREAD

**Issue by haoshuai714** [gingsi/coot-videotext#2]
Hello! I can't download the download link of Google cloud in China.Can you provide a Baidu cloud disk database download link? Thank you!

**Comment by gingsi** [comment]
Hi, we are working on providing a torrent, do you think that will work for you?

**Comment by gingsi** [comment]
Dataset is now available via torrent, please reopen this issue if that also doesn't work for you and you need a baidu link.

Best

**Comment by haoshuai714** [comment]
Thank you
