### ISSUE TITLE
Coot features for a new dataset

### ISSUE THREAD

**Issue by medhini** [gingsi/coot-videotext#20]
How do I go about extracting Coot visual embeddings only for a new dataset? Could you share code for creating the input h5 feature files?

**Comment by gingsi** [comment]
Hi,

For the youcook2 100m pretrained model extract the features as described here: https://github.com/gingsi/coot-videotext/issues/17

For the activitynet pretrained model you would have to read the paper of this repository https://github.com/Sha-Lab/CMHSE and replicate what they are doing.

You will have to create the h5 and the meta_all.json for your dataset, I suggest you run your pipeline on one of the videos in the existing dataset and check if you get similar output features, then run it on the new dataset.

If you build this pipeline, it would be very nice of you to share it here.

In the foreseeable future I will not have time to build an easier integration for new datasets.

Best,

**Comment by DesaleF** [comment]
@gingsi I was doing samething as @medhini But I doing know where to begin. I have extracted feature for activityNet using [anet-chulk](https://github.com/yjxiong/anet2016-cuhk), however it generates a .npy file for each video. So can you help me by just listing what you did to extract feature and create the h5 and meta_all.json files. To be honest I don't even know the structure of the h5 file that you use. By the way I am doing only the video captioning part so it will be very helpful if you specifically tell me how can I generate the h5 files for video captioning. If you tell me how you did it for activityNet, I will figure out for my videos. I will share it here if I succeed.

**Comment by gingsi** [comment]
Hi, not sure what exactly you want to do. Video captioning based on retrieval embeddings? Then you will need to train both retrieval and then captioning? Video captioning based on visual features only? Then you can skip retrieval.

This is what you need to do for video captioning based on video retrieval embeddings:

So as described in my last comment, we directly take the features from https://github.com/Sha-Lab/CMHSE 
These features are extracted to disk like this:
`dataset_path/features/ICEP_V3_global_pool_skip_8_direct_resize/v_XXXXXXXXXXX.npz`
The meta_all.json is created with the script `data_read_activitynet_meta.py`
Next you will need to use `precompute_text.py` to create the text features H5 file for your dataset.
Then you can train retrieval. You will need to change the config `dataset_train` fields `vid_feat_...`. Features will be loaded in file `coot/features_leader.py`. There is an explanation in the readme on how to extract features for captioning.
Next you need to create your vocabulary with `mart_build_vocab.py` to create files `annotations/DATASET/mart_word2idx.json` and `cache_caption/DATASET_vocab_glove.pt`.
Finally you copy the H5 embeddings created with retrieval to folder `provided_embeddings` and update your captioning config to the new embeddings.

Note that in the future we may provide code to make this process easier.

**Comment by DesaleF** [comment]
Thank you for your tremendous help. I followed the steps and it works now.
But in the future I may ask you about training video captioning without retrieval embeddings.
