### ISSUE TITLE
Does the pretrained model work for Chinese?

### ISSUE THREAD

**Issue by PipiZong** [gingsi/coot-videotext#21]
Hi,

Thanks for sharing! If I want to apply the pre-trained model for a small Chinese dataset (with videos), is it possible and flexible?

**Comment by gingsi** [comment]
The pretrained models for Retrieval and Captioning only understand English so you should train from scratch. I am pretty sure the models will not understand Chinese.

You will need to 1) for retrieval, extract text features with a pretrained Chinese BERT, GPT2, RoBERTa or similar model and 2) for retrieval or captioning, extract appearance and maybe optical flow features for the videos with pretrained networks Resnet, Resnext or similar. You could also try using the HowTo100M model for this extraction, however this will only work if your dataset is close to the 100m dataset.

Best
