### ISSUE TITLE
Is there any Google collab notebook available?

### ISSUE THREAD

**Issue by harshraj32** [gingsi/coot-videotext#22]
i am very keen on this project. but my computer isn't capable of downloading such high amounts of data. which is why can you please share the google collab link, with which i can at least run an instance of this project.

**Comment by gingsi** [comment]
Hi, you can run the youcook2 100m experiments which only need a couple of GB. Video captioning on the coot embeddings also doesn't require lots of data. Or you could make a notebook yourself. Best
