### ISSUE TITLE
python data_read_youcook2_meta.py where youcook2/meta_all.json?

### ISSUE THREAD

**Issue by jun0wanan** [gingsi/coot-videotext#27]

**Comment by jun0wanan** [comment]
> _No description provided._

hope to get your replay╥﹏╥...

**Comment by gingsi** [comment]
in the readme it tells you how to create meta_all.json

**Comment by gingsi** [comment]
As it says in the readme you should run this command to create meta_all.json `python data_read_youcook2_meta.py`

Please run this command and post the output here if it doesn't work
