### ISSUE TITLE
Does COOT uses ground truth timestamp to generate coherent caption(Paragraph)?

### ISSUE THREAD

**Issue by DesaleF** [gingsi/coot-videotext#28]
When generating captions for testing or validation did you use the ground truth timestamp to generate each sentence or COOT can just generate the paragraph caption without using the ground truth timestamp?

**Comment by gingsi** [comment]
We use ground-truth timestamps.

**Comment by DesaleF** [comment]
Okay!! Thank you. 
One more question: is there anyway to generate timestamp generation rather than using the ground truth. If you have any recommendation to generate  a coherent paragraph with a proposed timestamp by the network.

**Comment by gingsi** [comment]
You would need to use someone else's pretrained model for something like "dense event prediction" to get timestamps and then build the meta_all.json for your dataset with these new timestamps. Let us know if you find a good way to predict these timestamps.

**Comment by DesaleF** [comment]
Thank you very much for your suggestion.
I will check that and I will post it here if I got success to predict the timestamps.
