### ISSUE TITLE
where is youcookii_annotations_trainval.json

### ISSUE THREAD

**Issue by lzlzlizi** [gingsi/coot-videotext#3]
Hello, 

Thanks for releasing the codes. May I ask where is youcookii_annotations_trainval.json?

Thanks！

**Comment by gingsi** [comment]
Hello,

It was indeed missing, thanks!

I have pushed it now to data/youcook2/captions/youcookii_annotations_trainval.json

This is the same file as provided by the dataset creators here http://youcook2.eecs.umich.edu/download

Best

**Comment by lzlzlizi** [comment]
Thanks!
