### ISSUE TITLE
Can't download the Prepare pretrained models / embeddings 

### ISSUE THREAD

**Issue by gaoliming123** [gingsi/coot-videotext#30]
**Describe the bug**
Can you provide a torrent for pretrained models / embeddings. I can't download from the link of Google Drive

**Comment by gingsi** [comment]
Hi, please check if you can download these:

https://lmb.informatik.uni-freiburg.de/data/coot/provided_embeddings.tar.gz
https://lmb.informatik.uni-freiburg.de/data/coot/provided_models.tar.gz
