### ISSUE TITLE
Get error when train TransformerXL on COOT embeddings

### ISSUE THREAD

**Issue by menggehe** [gingsi/coot-videotext#32]
I am trying to train TransformerXL model on video captioning task. 
command: 
python train_caption.py -c config/caption/paper2020/anet_coot_vidclip_mart.yaml --coot_feat_dir embeddings

But I get an error when validation:
![image](https://user-images.githubusercontent.com/48981184/116773985-d4111f00-aa8b-11eb-9f31-6cc6db637f83.png)

Is there anything that you suggest I do?

**Comment by gingsi** [comment]
Hello, we currently don't support running TransformerXL with this repository. Check the original MART code, there you can run it:
https://github.com/jayleicn/recurrent-transformer

If you get TransformerXL running with this repo, please feel free to provide a pull request.

**Comment by menggehe** [comment]
Thank you very much!
