### ISSUE TITLE
About `TransformerEncoder`

### ISSUE THREAD

**Issue by lzlzlizi** [gingsi/coot-videotext#5]
```{Python}
sources = None
for encoder_layer in self.encoder_layers:
    sources = encoder_layer(query, key, value, mask)
```
This might be a silly question, but I am a little bit confused about the above code chunk, does't it just mean `sources = self.encoder_layers[-1](query, key, value, mask)`? 
If the codes are correct, could you please explain a little bit about how they works. 

Thanks!

**Comment by gingsi** [comment]
Hi,

Yes, this is bugged and means that the code only works correctly for 1 layer. However COOT only uses single layer building blocks so in the end it all works out fine.

We will probably fix this in the next release.

Best

**Comment by gingsi** [comment]
This has been fixed but COOT still doesn't improve with more than 1 layer in our experiments.
