### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/activitynet/captions/train.json'

### ISSUE THREAD

**Issue by haoshuai714** [gingsi/coot-videotext#7]
I have a error, when run:python prepare_activitynet.py 
FileNotFoundError: [Errno 2] No such file or directory: 'data/activitynet/captions/train.json
where I can download: train.json/val_1.json/val_2.json?

**Comment by gingsi** [comment]
Hi, sorry, the files were missing. I just pushed them. Please pull, check if it works and reopen the issue if it doesn't.

Best
